service: github-copilot-deployment-lambda-demo

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: src/index.hello # The handler is the file name (without the .js extension) and the exported function name
    events:
      - http:
          path: hello
          method: get