service: github-copilot-deployment-lambda-demo

provider:
  name: aws
  runtime: nodejs18.x # Node.js version to use for the Lambda function
  region: us-east-1 # AWS region where the Lambda function will be deployed

functions:
  hello:
    handler: src/index.hello # The handler is the file name (without the .js extension) and the exported function name
    events:
      - http:
          path: hello
          method: get