name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read # needed to checkout the repository's code.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::750344256621:role/CII-GitHub-Account-IAM-Role
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: us-east-1 # use your region here.
      # You can now execute commands that use the credentials👇
      # - name: Serverless deploy
      #   run: sls deploy --stage dev
      - name: Deploy to AWS Lambda
        run: npx serverless deploy


      # - name: Configure AWS credentials
      #   uses: fuller-inc/actions-aws-assume-role@v1
      #   with:
      #     role-to-assume: arn:aws:iam::750344256621:role/CII-GitHub-Account-IAM-Role
      #     role-session-name: GitHubActions
      #     aws-region: us-east-1
      # - name: Sts GetCallerIdentity
      #   run: |
      #     aws sts get-caller-identity





